site_title: Gallerize Title
site_url: '.'
output_path: gallerize

images_per_page: 40

file_patterns:
  - "*.jpg"
  - "*.png"
  - "*.gif"

versions:
  thumb:
    width: 400
    height: 250
    approach: crop

  large:
    width: 1000
    height: 800
    approach: resize

parallel:
  in_processes: 6