output_path: gallerize

file_patterns:
  - "*.jpg"
  - "*.png"
  - "*.gif"

versions:
  thumb:
    width: 250
    height: 300

  large:
    width: 800
    height: 600

  full:
    width: 1600
    height: 1200