site_title: Gallerize Title
site_url: '.'
output_path: gallerize

file_patterns:
  - "*.jpg"
  - "*.png"
  - "*.gif"

versions:
  thumb:
    width: 250
    height: 300

  large:
    width: 800
    height: 600
