site_title:
site_url: '.'
output_path: gallerize

images_per_page: 40

file_patterns:
  - "*.jpg"
  - "*.jpeg"
  - "*.png"
  - "*.gif"

versions:
  thumb:
    width: 400
    height: 300
    crop: true

  large:
    width: 1600
    height: 1200
    crop: false

parallel:
  in_processes: 8

image_attributes:
  example.jpg:
    title: The Title