site_title: Gallerize Title
site_url: '.'
output_path: gallerize

images_per_page: 2

file_patterns:
  - "*.jpg"
  - "*.png"
  - "*.gif"

versions:
  thumb:
    width: 250
    height: 300

  large:
    width: 800
    height: 600


parallel:
  in_processes: 6